# Generated by Django 4.1.5 on 2023-01-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
    ]
